### PR TITLE
pass in ignore_regex option to ignore files from taking a snapshot

### PR DESCRIPTION
**Pull request by bostonaholic**
This adds the ability to pass in the `--ignore_regex` option to ignore certain files from taking a snapshot.

My use case:
I have a static site that is using JavaScript on a page to randomize some seed data. I'd prefer to just skip snapshots on this page entirely.

### CODE REVIEW

**Comment by timhaines** [comment]
Thanks @bostonaholic!  We'll take a look at this asap.  

Ignore the linting failures in CI - they're caused by our central styles being updated very recently, and this repo not being updated yet to stay inline with them.  I'll fix that.

**Comment by bostonaholic** [comment]
@timhaines feel free to push any changes you see fit!

**Comment by bostonaholic** [comment]
@timhaines I made the changes but it's still failing on Travis. **Maybe the `rubocop.yml` rules need updated?** It's failing in the ruby 2.1 and 2.2 builds with the same `undefined method 'match?' for #<String:0x0000000439c318>` error, even though ruby 2.1 and 2.2 don't have `String#match`.

**Comment by timhaines** [comment]
I think we're likely to drop Ruby 2.1 from the travis config too, seeing as it's unsupported now.

**Comment by faun** [comment]
This has been merged. If you rebase off `percy:master`, I believe this PR will be marked as merged.

**Comment by faun** [comment]
I'm going to close this issue, since all commits have been merged to master.

**Pull request closed without merging**
